

USE DBUsers


CREATE TABLE Users
(

Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
[NAME] NVARCHAR(50) NOT NULL,
[SURNAME] NVARCHAR(50) NOT NULL,
[AGE] INT NOT NULL,
[LOGIN] NVARCHAR(30) NOT NULL,
[PASSWORD] NVARCHAR(30) NOT NULL

)